name: Docker Build and Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-check:
    name: Build and Scan Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Webserver Image
        run: docker build -t blocklist-webserver:latest -f dockerfile.app .

      - name: Build Scheduler Image
        run: docker build -t blocklist-scheduler:latest -f dockerfile.scheduler .

      - name: Run Trivy scanner (Webserver Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'blocklist-webserver:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy scanner (Scheduler Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'blocklist-scheduler:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
