name: Docker Build and Check

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  build-and-check:
    name: Build and Scan Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Webserver Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile.app
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-webserver:latest

      - name: Build and push Scheduler Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile.scheduler
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-scheduler:latest

      - name: Run Trivy scanner (Webserver Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}-webserver:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy scanner (Scheduler Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}-scheduler:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
